/*
   Choose Your Own Adventure!
*/

#include "define.h"

procedure start begin
   variable mysterious_person;

   if game_loaded then begin
      // gfade_out(420);
      // load_map("rndforvr", 18495);
      mysterious_person = create_object(PID_HERO_ROBE, 17094, 0);
      remove_script(mysterious_person);
      critter_attempt_placement(mysterious_person, 17094, 0);
      // gfade_in(420);



      // sleep

//      face_critter
   end
end